# Generated by Django 2.2.16 on 2022-04-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220414_1836'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='uniq_name',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='uniq_follow'),
        ),
    ]
